import 'riscv_isa_base.dart';
import 'riscv_isa_decode.dart';
import 'ops.dart';

/// RV32I extension
///
/// {@category extensions}
const rv32i = RiscVExtension(
  [
    Operation<UType>(
      mnemonic: 'lui',
      opcode: 0x37,
      struct: UType.STRUCT,
      constructor: UType.map,
      microcode: [
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.imm),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<UType>(
      mnemonic: 'auipc',
      opcode: 0x17,
      struct: UType.STRUCT,
      constructor: UType.map,
      microcode: [
        AluMicroOp(MicroOpAluFunct.add, MicroOpField.pc, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<JType>(
      mnemonic: 'jal',
      opcode: 0x6F,
      struct: JType.STRUCT,
      constructor: JType.map,
      microcode: [
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.pc, valueOffset: 4),
        UpdatePCMicroOp(MicroOpField.pc, offsetField: MicroOpField.imm),
      ],
    ),
    Operation<IType>(
      mnemonic: 'jalr',
      opcode: 0x67,
      funct3: 0x0,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.imm, offset: 4),
        AluMicroOp(MicroOpAluFunct.add, MicroOpField.rs1, MicroOpField.imm),
        UpdatePCMicroOp(MicroOpField.pc, offsetField: MicroOpField.imm),
      ],
    ),
    Operation<BType>(
      mnemonic: 'beq',
      opcode: 0x63,
      funct3: 0x0,
      struct: BType.STRUCT,
      constructor: BType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.sub, MicroOpField.rs1, MicroOpField.rs2),
        BranchIfMicroOp(
          MicroOpCondition.eq,
          MicroOpSource.alu,
          offsetField: MicroOpField.imm,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<BType>(
      mnemonic: 'bne',
      opcode: 0x63,
      funct3: 0x1,
      struct: BType.STRUCT,
      constructor: BType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.sub, MicroOpField.rs1, MicroOpField.rs2),
        BranchIfMicroOp(
          MicroOpCondition.ne,
          MicroOpSource.alu,
          offsetField: MicroOpField.imm,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<BType>(
      mnemonic: 'blt',
      opcode: 0x63,
      funct3: 0x2,
      struct: BType.STRUCT,
      constructor: BType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.slt, MicroOpField.rs1, MicroOpField.rs2),
        BranchIfMicroOp(
          MicroOpCondition.ne,
          MicroOpSource.alu,
          offsetField: MicroOpField.imm,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<BType>(
      mnemonic: 'bge',
      opcode: 0x63,
      funct3: 0x5,
      struct: BType.STRUCT,
      constructor: BType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.slt, MicroOpField.rs1, MicroOpField.rs2),
        BranchIfMicroOp(
          MicroOpCondition.eq,
          MicroOpSource.alu,
          offsetField: MicroOpField.imm,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<BType>(
      mnemonic: 'bltu',
      opcode: 0x63,
      funct3: 0x6,
      struct: BType.STRUCT,
      constructor: BType.map,
      microcode: [
        AluMicroOp(MicroOpAluFunct.sltu, MicroOpField.rs1, MicroOpField.rs2),
        BranchIfMicroOp(
          MicroOpCondition.ne,
          MicroOpSource.alu,
          offsetField: MicroOpField.imm,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<BType>(
      mnemonic: 'bgeu',
      opcode: 0x63,
      funct3: 0x7,
      struct: BType.STRUCT,
      constructor: BType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.sltu, MicroOpField.rs1, MicroOpField.rs2),
        BranchIfMicroOp(
          MicroOpCondition.eq,
          MicroOpSource.alu,
          offsetField: MicroOpField.imm,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'lb',
      opcode: 0x03,
      funct3: 0x0,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        MemLoadMicroOp(
          base: MicroOpField.rs1,
          size: MicroOpMemSize.byte,
          unsigned: false,
          dest: MicroOpField.rd,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'lh',
      opcode: 0x03,
      funct3: 0x1,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        MemLoadMicroOp(
          base: MicroOpField.rs1,
          size: MicroOpMemSize.half,
          unsigned: false,
          dest: MicroOpField.rd,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'lw',
      opcode: 0x03,
      funct3: 0x2,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        MemLoadMicroOp(
          base: MicroOpField.rs1,
          size: MicroOpMemSize.word,
          unsigned: true,
          dest: MicroOpField.rs2,
        ),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.rs2),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'lbu',
      opcode: 0x03,
      funct3: 0x4,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        MemLoadMicroOp(
          base: MicroOpField.rs1,
          size: MicroOpMemSize.byte,
          unsigned: true,
          dest: MicroOpField.rs2,
        ),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.rs2),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'lhu',
      opcode: 0x03,
      funct3: 0x5,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        MemLoadMicroOp(
          base: MicroOpField.rs1,
          size: MicroOpMemSize.half,
          unsigned: true,
          dest: MicroOpField.rd,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<SType>(
      mnemonic: 'sb',
      opcode: 0x23,
      funct3: 0x0,
      struct: SType.STRUCT,
      constructor: SType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        MemStoreMicroOp(
          base: MicroOpField.rs1,
          src: MicroOpField.rs2,
          size: MicroOpMemSize.byte,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<SType>(
      mnemonic: 'sh',
      opcode: 0x23,
      funct3: 0x1,
      struct: SType.STRUCT,
      constructor: SType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        MemStoreMicroOp(
          base: MicroOpField.rs1,
          src: MicroOpField.rs2,
          size: MicroOpMemSize.half,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<SType>(
      mnemonic: 'sw',
      opcode: 0x23,
      funct3: 0x2,
      struct: SType.STRUCT,
      constructor: SType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        MemStoreMicroOp(
          base: MicroOpField.rs1,
          src: MicroOpField.rs2,
          size: MicroOpMemSize.word,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'addi',
      opcode: 0x13,
      funct3: 0x0,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.add, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'slti',
      opcode: 0x13,
      funct3: 0x2,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.slt, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'sltiu',
      opcode: 0x13,
      funct3: 0x3,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.sltu, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'xori',
      opcode: 0x13,
      funct3: 0x4,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.xor, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'ori',
      opcode: 0x13,
      funct3: 0x6,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.or, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'andi',
      opcode: 0x13,
      funct3: 0x7,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.and, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'slli',
      opcode: 0x13,
      funct3: 0x1,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.sll, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'srli',
      opcode: 0x13,
      funct3: 0x5,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.srl, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'srai',
      opcode: 0x13,
      funct3: 0x5,
      funct7: 0x20,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.sra, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<RType>(
      mnemonic: 'add',
      opcode: 0x33,
      funct3: 0x0,
      funct7: 0x00,
      struct: RType.STRUCT,
      constructor: RType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.add, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<RType>(
      mnemonic: 'sub',
      opcode: 0x33,
      funct3: 0x0,
      funct7: 0x20,
      struct: RType.STRUCT,
      constructor: RType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.sub, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<RType>(
      mnemonic: 'sll',
      opcode: 0x33,
      funct3: 0x1,
      funct7: 0x00,
      struct: RType.STRUCT,
      constructor: RType.map,
      microcode: [
        AluMicroOp(MicroOpAluFunct.sll, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<RType>(
      mnemonic: 'slt',
      opcode: 0x33,
      funct3: 0x2,
      funct7: 0x00,
      struct: RType.STRUCT,
      constructor: RType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.slt, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<RType>(
      mnemonic: 'sltu',
      opcode: 0x33,
      funct3: 0x3,
      funct7: 0x00,
      struct: RType.STRUCT,
      constructor: RType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.sltu, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<RType>(
      mnemonic: 'xor',
      opcode: 0x33,
      funct3: 0x4,
      funct7: 0x00,
      struct: RType.STRUCT,
      constructor: RType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.xor, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<RType>(
      mnemonic: 'srl',
      opcode: 0x33,
      funct3: 0x5,
      funct7: 0x00,
      struct: RType.STRUCT,
      constructor: RType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.srl, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<RType>(
      mnemonic: 'sra',
      opcode: 0x33,
      funct3: 0x5,
      funct7: 0x20,
      struct: RType.STRUCT,
      constructor: RType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.sra, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<RType>(
      mnemonic: 'or',
      opcode: 0x33,
      funct3: 0x6,
      funct7: 0x00,
      struct: RType.STRUCT,
      constructor: RType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.or, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<RType>(
      mnemonic: 'and',
      opcode: 0x33,
      funct3: 0x7,
      funct7: 0x00,
      struct: RType.STRUCT,
      constructor: RType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.and, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'fence',
      opcode: 0x0F,
      funct3: 0x0,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [FenceMicroOp(), UpdatePCMicroOp(MicroOpField.pc, offset: 4)],
    ),
    Operation<IType>(
      mnemonic: 'ecall',
      opcode: 0x73,
      funct3: 0x0,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [TrapMicroOp(Trap.ecallM, Trap.ecallS, Trap.ecallU)],
    ),
    Operation<IType>(
      mnemonic: 'ebreak',
      opcode: 0x73,
      funct3: 0x0,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [TrapMicroOp.one(Trap.breakpoint)],
    ),
  ],
  name: 'RV32I',
  key: 'I',
  mask: 1 << 8,
);
