import 'riscv_isa_base.dart';
import 'riscv_isa_decode.dart';
import 'ops.dart';

/// RV64I extension
///
/// {@category extensions}
const rv64i = RiscVExtension(
  [
    Operation<IType>(
      mnemonic: 'lwu',
      opcode: 0x03,
      funct3: 0x6,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        MemLoadMicroOp(
          base: MicroOpField.rs1,
          size: MicroOpMemSize.word,
          unsigned: true,
          dest: MicroOpField.rd,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'ld',
      opcode: 0x03,
      funct3: 0x3,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        MemLoadMicroOp(
          base: MicroOpField.rs1,
          size: MicroOpMemSize.dword,
          unsigned: true,
          dest: MicroOpField.rd,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<SType>(
      mnemonic: 'sd',
      opcode: 0x23,
      funct3: 0x3,
      struct: SType.STRUCT,
      constructor: SType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        MemStoreMicroOp(
          base: MicroOpField.rs1,
          src: MicroOpField.rs2,
          size: MicroOpMemSize.dword,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'addiw',
      opcode: 0x1B,
      funct3: 0x0,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.add, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'slliw',
      opcode: 0x1B,
      funct3: 0x1,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.sll, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'srliw',
      opcode: 0x1B,
      funct3: 0x5,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.srl, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<IType>(
      mnemonic: 'sraiw',
      opcode: 0x1B,
      funct3: 0x5,
      funct7: 0x20,
      struct: IType.STRUCT,
      constructor: IType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.sra, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<RType>(
      mnemonic: 'addw',
      opcode: 0x3B,
      funct3: 0x0,
      funct7: 0x00,
      struct: RType.STRUCT,
      constructor: RType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.add, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<RType>(
      mnemonic: 'subw',
      opcode: 0x3B,
      funct3: 0x0,
      funct7: 0x20,
      struct: RType.STRUCT,
      constructor: RType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.sub, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<RType>(
      mnemonic: 'sllw',
      opcode: 0x3B,
      funct3: 0x1,
      funct7: 0x00,
      struct: RType.STRUCT,
      constructor: RType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.sll, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<RType>(
      mnemonic: 'srlw',
      opcode: 0x3B,
      funct3: 0x5,
      funct7: 0x00,
      struct: RType.STRUCT,
      constructor: RType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.srl, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
    Operation<RType>(
      mnemonic: 'sraw',
      opcode: 0x3B,
      funct3: 0x5,
      funct7: 0x20,
      struct: RType.STRUCT,
      constructor: RType.map,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.sra, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 4),
      ],
    ),
  ],
  name: 'RV64I',
  key: 'I',
  mask: 1 << 8,
);
