import '../../ops.dart';
import '../../riscv_isa_base.dart';
import 'decode.dart';
import 'isa.dart';

const rvc = RiscVExtension(
  [
    Operation<CompressedWIType>(
      mnemonic: 'c.addi4spn',
      opcode: 0x0,
      funct3: 0x0,
      decode: CompressedWITypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.sp),
        AluMicroOp(MicroOpAluFunct.add, MicroOpField.sp, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedIType>(
      mnemonic: 'c.addi',
      opcode: 0x1,
      funct3: 0x0,
      decode: CompressedITypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.add, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedAType>(
      mnemonic: 'c.andi',
      opcode: 0x1,
      funct3: 0x7,
      decode: CompressedATypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.and, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedAType>(
      mnemonic: 'c.and',
      opcode: 0x2,
      funct3: 0x4,
      decode: CompressedATypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.and, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedLType>(
      mnemonic: 'c.lw',
      opcode: 0x0,
      funct3: 0x2,
      decode: CompressedLTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        MemLoadMicroOp(
          base: MicroOpField.rs1,
          size: MicroOpMemSize.word,
          unsigned: false,
          dest: MicroOpField.rd,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedSType>(
      mnemonic: 'c.sw',
      opcode: 0x0,
      funct3: 0x6,
      decode: CompressedSTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        MemStoreMicroOp(
          base: MicroOpField.rs1,
          src: MicroOpField.rs2,
          size: MicroOpMemSize.word,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedJType>(
      mnemonic: 'c.j',
      opcode: 0x1,
      funct3: 0x5,
      decode: CompressedJTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        WriteRegisterMicroOp(MicroOpField.pc, MicroOpSource.imm),
        UpdatePCMicroOp(MicroOpField.pc, offsetField: MicroOpField.imm),
      ],
    ),
    Operation<CompressedIType>(
      mnemonic: 'c.li',
      opcode: 0x1,
      funct3: 0x2,
      decode: CompressedITypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.imm),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedRType>(
      mnemonic: 'c.mv',
      opcode: 0x2,
      funct3: 0x4,
      decode: CompressedRTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.rs2),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedRType>(
      mnemonic: 'c.add',
      opcode: 0x2,
      funct3: 0x4,
      decode: CompressedRTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.add, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedSSType>(
      mnemonic: 'c.lwsp',
      opcode: 0x2,
      funct3: 0x2,
      decode: CompressedSSTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.sp),
        MemLoadMicroOp(
          base: MicroOpField.sp,
          size: MicroOpMemSize.word,
          unsigned: false,
          dest: MicroOpField.rd,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedAType>(
      mnemonic: 'c.srli',
      opcode: 0x1,
      funct3: 0x4,
      decode: CompressedATypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.srl, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedAType>(
      mnemonic: 'c.srai',
      opcode: 0x1,
      funct3: 0x4,
      decode: CompressedATypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.sra, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedAType>(
      mnemonic: 'c.sub',
      opcode: 0x1,
      funct3: 0x4,
      decode: CompressedATypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.sub, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedAType>(
      mnemonic: 'c.xor',
      opcode: 0x1,
      funct3: 0x4,
      decode: CompressedATypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.xor, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedAType>(
      mnemonic: 'c.or',
      opcode: 0x1,
      funct3: 0x4,
      decode: CompressedATypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.or, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedIType>(
      mnemonic: 'c.addi16sp',
      opcode: 0x1,
      funct3: 0x3,
      decode: CompressedITypeDecode.decode,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.sp),
        AluMicroOp(MicroOpAluFunct.add, MicroOpField.sp, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.sp, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedIType>(
      mnemonic: 'c.lui',
      opcode: 0x1,
      funct3: 0x3,
      decode: CompressedITypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.imm),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedBType>(
      mnemonic: 'c.beqz',
      opcode: 0x1,
      funct3: 0x6,
      decode: CompressedBTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        BranchIfZeroMicroOp(
          field: MicroOpField.rs1,
          offsetField: MicroOpField.imm,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedBType>(
      mnemonic: 'c.bnez',
      opcode: 0x1,
      funct3: 0x7,
      decode: CompressedBTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        BranchIfNonZeroMicroOp(
          field: MicroOpField.rs1,
          offsetField: MicroOpField.imm,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedIType>(
      mnemonic: 'c.slli',
      opcode: 0x2,
      funct3: 0x0,
      decode: CompressedITypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.sll, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedRType>(
      mnemonic: 'c.jr',
      opcode: 0x2,
      funct3: 0x4,
      decode: CompressedRTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [UpdatePCMicroOp(MicroOpField.rs1, offset: 0)],
    ),
    Operation<CompressedRType>(
      mnemonic: 'c.jalr',
      opcode: 0x2,
      funct3: 0x4,
      decode: CompressedRTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        WriteLinkRegisterMicroOp(link: MicroOpLink.ra, pcOffset: 2),
        UpdatePCMicroOp(MicroOpField.rs1, offset: 0),
      ],
    ),
    Operation<CompressedRType>(
      mnemonic: 'c.ebreak',
      opcode: 0x2,
      funct3: 0x4,
      decode: CompressedRTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [TrapMicroOp.one(Trap.breakpoint)],
    ),
    Operation<CompressedSSType>(
      mnemonic: 'c.swsp',
      opcode: 0x2,
      funct3: 0x6,
      decode: CompressedSSTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.sp),
        ReadRegisterMicroOp(MicroOpField.rs2),
        MemStoreMicroOp(
          base: MicroOpField.sp,
          src: MicroOpField.rs2,
          size: MicroOpMemSize.word,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
  ],
  mask: 1 << 2,
  name: 'RVC',
  key: 'C',
);
