import '../../ops.dart';
import '../../riscv_isa_base.dart';
import 'decode.dart';
import 'isa.dart';

const rvc = RiscVExtension(
  [
    Operation<CompressedWIType>(
      mnemonic: 'c.addi4spn',
      opcode: 0x0,
      funct3: 0x0,
      decode: CompressedWITypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ValidateImmediateNonZeroMicroOp(),
        AluMicroOp(MicroOpAluFunct.add, MicroOpField.sp, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu, offset: 8),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedIType>(
      mnemonic: 'c.addi',
      opcode: 0x1,
      funct3: 0x0,
      decode: CompressedITypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.add, MicroOpField.rs1, MicroOpField.imm),
        ModifyLatchMicroOp(MicroOpField.rs1, MicroOpSource.rs1, false),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedAType>(
      mnemonic: 'c.andi',
      opcode: 0x1,
      funct3: 0x7,
      decode: CompressedATypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1, offset: 8),
        AluMicroOp(MicroOpAluFunct.and, MicroOpField.rs1, MicroOpField.imm),
        ModifyLatchMicroOp(MicroOpField.rs1, MicroOpSource.rs1, false),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedAType>(
      mnemonic: 'c.and',
      opcode: 0x1,
      funct2: 0x3,
      funct6: 0x23,
      decode: CompressedATypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1, offset: 8),
        ReadRegisterMicroOp(MicroOpField.rs2, offset: 8),
        AluMicroOp(MicroOpAluFunct.and, MicroOpField.rs1, MicroOpField.rs2),
        ModifyLatchMicroOp(MicroOpField.rs1, MicroOpSource.rs1, false),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu, offset: 8),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedLType>(
      mnemonic: 'c.lw',
      opcode: 0x0,
      funct3: 0x2,
      decode: CompressedLTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1, offset: 8),
        MemLoadMicroOp(
          base: MicroOpField.rs1,
          size: MicroOpMemSize.word,
          unsigned: true,
          dest: MicroOpField.rs2,
        ),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.rs2, offset: 8),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedSType>(
      mnemonic: 'c.sw',
      opcode: 0x0,
      funct3: 0x6,
      decode: CompressedSTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1, offset: 8),
        ReadRegisterMicroOp(MicroOpField.rs2, offset: 8),
        MemStoreMicroOp(
          base: MicroOpField.rs1,
          src: MicroOpField.rs2,
          size: MicroOpMemSize.word,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedJType>(
      mnemonic: 'c.j',
      opcode: 0x1,
      funct3: 0x5,
      decode: CompressedJTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        WriteRegisterMicroOp(MicroOpField.pc, MicroOpSource.imm),
        UpdatePCMicroOp(MicroOpField.pc, offsetField: MicroOpField.imm),
      ],
    ),
    Operation<CompressedIType>(
      mnemonic: 'c.li',
      opcode: 0x1,
      funct3: 0x2,
      decode: CompressedITypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.imm),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedRType>(
      mnemonic: 'c.mv',
      opcode: 0x2,
      funct4: 0x8,
      decode: CompressedRTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      nonZeroFields: ['rs2'],
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.rs2),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedRType>(
      mnemonic: 'c.add',
      opcode: 0x2,
      funct4: 0x9,
      decode: CompressedRTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      nonZeroFields: ['rs1', 'rs2'],
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        ReadRegisterMicroOp(MicroOpField.rs2),
        AluMicroOp(MicroOpAluFunct.add, MicroOpField.rs1, MicroOpField.rs2),
        ModifyLatchMicroOp(MicroOpField.rs1, MicroOpSource.rs1, false),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedLwspType>(
      mnemonic: 'c.lwsp',
      opcode: 0x2,
      funct3: 0x2,
      decode: CompressedLwspTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        MemLoadMicroOp(
          base: MicroOpField.sp,
          size: MicroOpMemSize.word,
          unsigned: true,
          dest: MicroOpField.rs1,
        ),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.rs1),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedCbType>(
      mnemonic: 'c.srli',
      opcode: 0x1,
      funct2: 0,
      funct3: 0x4,
      decode: CompressedCbTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1, offset: 8),
        AluMicroOp(MicroOpAluFunct.srl, MicroOpField.rs1, MicroOpField.imm),
        ModifyLatchMicroOp(MicroOpField.rs1, MicroOpSource.rs1, false),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu, offset: 8),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedCbType>(
      mnemonic: 'c.srai',
      opcode: 0x1,
      funct2: 1,
      funct3: 0x4,
      decode: CompressedCbTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        AluMicroOp(MicroOpAluFunct.sra, MicroOpField.rs1, MicroOpField.imm),
        ModifyLatchMicroOp(MicroOpField.rs1, MicroOpSource.rs1, false),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedAType>(
      mnemonic: 'c.sub',
      opcode: 0x1,
      funct3: 0x4,
      decode: CompressedATypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1, offset: 8),
        ReadRegisterMicroOp(MicroOpField.rs2, offset: 8),
        AluMicroOp(MicroOpAluFunct.sub, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedAType>(
      mnemonic: 'c.xor',
      opcode: 0x1,
      funct3: 0x4,
      decode: CompressedATypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1, offset: 8),
        ReadRegisterMicroOp(MicroOpField.rs2, offset: 8),
        AluMicroOp(MicroOpAluFunct.xor, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedAType>(
      mnemonic: 'c.or',
      opcode: 0x1,
      funct3: 0x4,
      decode: CompressedATypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1, offset: 8),
        ReadRegisterMicroOp(MicroOpField.rs2, offset: 8),
        AluMicroOp(MicroOpAluFunct.or, MicroOpField.rs1, MicroOpField.rs2),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu, offset: 8),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedIType>(
      mnemonic: 'c.addi16sp',
      opcode: 0x1,
      funct3: 0x3,
      decode: CompressedITypeDecode.decode,
      microcode: [
        AluMicroOp(MicroOpAluFunct.add, MicroOpField.sp, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.sp, MicroOpSource.alu, offset: 8),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedIType>(
      mnemonic: 'c.lui',
      opcode: 0x1,
      funct3: 0x3,
      decode: CompressedITypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        SetFieldMicroOp(MicroOpField.rs1, 12),
        AluMicroOp(MicroOpAluFunct.sll, MicroOpField.imm, MicroOpField.rs1),
        WriteRegisterMicroOp(MicroOpField.rd, MicroOpSource.alu, offset: 8),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedBType>(
      mnemonic: 'c.beqz',
      opcode: 0x1,
      funct3: 0x6,
      decode: CompressedBTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1, offset: 8),
        BranchIfMicroOp(
          MicroOpCondition.eq,
          MicroOpSource.rs1,
          offsetField: MicroOpField.imm,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedBType>(
      mnemonic: 'c.bnez',
      opcode: 0x1,
      funct3: 0x7,
      decode: CompressedBTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        BranchIfMicroOp(
          MicroOpCondition.ne,
          MicroOpSource.rs1,
          offsetField: MicroOpField.imm,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedIType>(
      mnemonic: 'c.slli',
      opcode: 0x2,
      funct3: 0x0,
      decode: CompressedITypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1, offset: 8),
        AluMicroOp(MicroOpAluFunct.sll, MicroOpField.rs1, MicroOpField.imm),
        WriteRegisterMicroOp(MicroOpField.rs1, MicroOpSource.alu, offset: 8),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
    Operation<CompressedRType>(
      mnemonic: 'c.jr',
      opcode: 0x2,
      funct4: 0x8,
      decode: CompressedRTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      zeroFields: ['rs2'],
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1, offset: 0),
        UpdatePCMicroOp(MicroOpField.rs1, offsetField: MicroOpField.rs1),
      ],
    ),
    Operation<CompressedRType>(
      mnemonic: 'c.jalr',
      opcode: 0x2,
      funct4: 0x9,
      decode: CompressedRTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs1),
        WriteLinkRegisterMicroOp(link: MicroOpLink.ra, pcOffset: 2),
        UpdatePCMicroOp(MicroOpField.rs1, offsetField: MicroOpField.rs1),
      ],
    ),
    Operation<CompressedRType>(
      mnemonic: 'c.ebreak',
      opcode: 0x2,
      funct3: 0x4,
      decode: CompressedRTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [TrapMicroOp.one(Trap.breakpoint)],
    ),
    Operation<CompressedSwspType>(
      mnemonic: 'c.swsp',
      opcode: 0x2,
      funct3: 0x6,
      decode: CompressedSwspTypeDecode.decode,
      opcodeRange: CompressedInstruction.opcodeRange,
      microcode: [
        ReadRegisterMicroOp(MicroOpField.rs2),
        MemStoreMicroOp(
          base: MicroOpField.sp,
          src: MicroOpField.rs2,
          size: MicroOpMemSize.word,
        ),
        UpdatePCMicroOp(MicroOpField.pc, offset: 2),
      ],
    ),
  ],
  mask: 1 << 2,
  name: 'RVC',
  key: 'C',
);
